GENERATED_DATA_DIR = './generated_data'

SENTIMENT_DATA_DIR = f'{GENERATED_DATA_DIR}/sentiment'
ANALYTICS_DIR = f'{GENERATED_DATA_DIR}/analytics'
BERTOPIC_DIR = f'{GENERATED_DATA_DIR}/bertopic'

BERTOPIC_DATA_DIR = f'{BERTOPIC_DIR}/data'
BERTOPIC_MODELS_DIR = f'{BERTOPIC_DIR}/models'
BERTOPIC_LOGS_DIR = f'{BERTOPIC_DIR}/logs' 
