GENERATED_DATA_DIR = './generated_data'

ANALYTICS_DIR = f'{GENERATED_DATA_DIR}/analytics'
ANIMATION_DATA_DIR = f'{GENERATED_DATA_DIR}/animation'
BERTOPIC_DIR = f'{GENERATED_DATA_DIR}/bertopic'
GANTT_DATA_DIR = f'{GENERATED_DATA_DIR}/gantt'
SENTIMENT_DATA_DIR = f'{GENERATED_DATA_DIR}/sentiment'

BERTOPIC_DATA_DIR = f'{BERTOPIC_DIR}/data'
BERTOPIC_MODELS_DIR = f'{BERTOPIC_DIR}/models'
BERTOPIC_LOGS_DIR = f'{BERTOPIC_DIR}/logs' 
