name: Deploy

on:
  push:
    branches:
      - heroku-prep
      - master

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15  # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "transcript-playground"
          heroku_email: "andyshirey@gmail.com"
          usedocker: true


# Reference: https://github.com/marketplace/actions/deploy-to-heroku
